### ISSUE TITLE
Make logic to generate names for generic types configurable

### ISSUE THREAD

**Issue by mnonnenmacher** [SMILEY4/schema-kenerator#13]
When using `withAutoTitle(TitleType.SIMPLE)` and `compileReferencingRoot(RefType.SIMPLE)` from schema-kenerator-swagger, the generated names for generic types like `GenericType<Type1, Type2>` contain angle brackets and commas: `GenericType<Type1,Type2>`.

This leads to problems with other tools consuming the generated schema because, according to the [specification](https://swagger.io/specification/#components-object), keys in the schemas map must match the regular expression `^[a-zA-Z0-9\.\-_]+$`.

I could work around this by making copies of `SwaggerSchemaAutoTitleStep`, `SwaggerSchemaCompileReferenceRootStep`, `SwaggerSchemaCompileReferenceStep`, and `SwaggerSchemaCompileUtils.getRefPath` and adapting the logic to generate titles and references to use only valid characters. In my case I have changed

```kotlin
val paramString = typeData.typeParameters
    .map { (_, param) -> getRefPath(pathType, typeDataMap[param.type]!!, typeDataMap) }
    .joinToString(",")
"$it<$paramString>"
```

to 

```kotlin
val paramString = typeData.typeParameters
    .map { (_, param) -> getRefPath(pathType, typeDataMap[param.type]!!, typeDataMap) }
    .joinToString("-")
"${it}_$paramString"
```

which generates the title as `GenericType_Type1-Type2`.

It would be great if this could be made configurable, for example by providing a function to do the conversion which defaults to the current behavior:

```kotlin
generateTitle: (type: String, children: List<String>) -> String = { type, children ->
    "$type<${children.joinToString { "," }}>"
}
```

**Comment by SMILEY4** [comment]
Hi,
Thank you for reporting the issue and for the suggestion. I created version 1.2.0 that adds the ability to customize the title and path by providing an own function. I also added new TitleType and RefType "OPENAPI_FULL" and "OPENAPI_SIMPLE" that conform to the openapi spec (i.e. i used your format :) )
ktor-swagger-ui should receive a new version soon aswell.

**Comment by mnonnenmacher** [comment]
Thank you very much! I will give `OPENAPI_SIMPLE` a try then.

**Comment by mnonnenmacher** [comment]
I found a small bug with `OPENAPI_SIMPLE`, see #15.
