### ISSUE TITLE
Support for Schema annotation with kotlin serialization is missing

### ISSUE THREAD

**Issue by NecroKote** [SMILEY4/schema-kenerator#17]
Hi, 
`@Schema` annotation doesn't work while using kotlin serialisation.

(This is due to the fact that this annotation is missing `@SerialInfo` and is removed during serialiser generation.)

I was hoping to use `@Schema` to alter field's `format`.
For example:
```kotlin
@Serializable
class Test {
    @Schema(format="uuid")
    val uuid: String
}
```

For now, I'm using a workaround where I have my own annotation `@Format` and own extension to process it in a similar way that `SwaggerSchemaCoreAnnotationDefaultStep` does

**Comment by SMILEY4** [comment]
Hi,
without the `@SerialInfo` unfortunately there isn't really anything i could to to get the information as far as i know.
It would work with the reflection step instead of kotlinx, but if that is not an option for you, i think your "workaround" is a completely valid option.

**Comment by NecroKote** [comment]
Understandable, thanks for quick response!

How do you feel about "mirroring" the fields of Schema annotation within kotlin serialization module as individual annotations? (Similar to Default and Required from Core)

**Comment by SMILEY4** [comment]
Not completely against such a new annotation. If the need is there, i'll have a look at it.

**Comment by rmcmk** [comment]
Our team would be interested a full subset of individual property annotations that map to the `@Schema` variant.

**Comment by rmcmk** [comment]
#36 adds support for `@Format`

**Comment by rmcmk** [comment]
What are your thoughts on using reflection to find metadata about the descriptors (Such as annotations)? I understand this goes against the whole idea of the generators being the way they are.

Maybe an explicit opt-in on the generator itself or on the `handleXYZAnnotations()` steps?

**Comment by rmcmk** [comment]
What are your thoughts on using reflection to find metadata about the descriptors, such as annotations? I understand that this approach goes against the fundamental design of the generators as they currently are.

Perhaps there could be an explicit opt-in on the generator itself or within the `handleXYZAnnotations()` steps?

Alternatively, we might consider providing core annotations for all of the [necessary] Swagger properties to maintain parity.

**Comment by SMILEY4** [comment]
I wouldn't do it with a config-option in the generator or processing step since that would mean adding logic to steps that are otherwise not responsible for that (e.g. generator should work the same independent of whether the inputs come from reflection or kotlinx). Apart from that we may still not have access to the annotations - i dont think the kotlinx descriptors keep a reference to a type that can be used with reflection (i might need to check that).

I think the best approach would be to add annotations or a drop-in replacement annotation for `@Schema`.
