### ISSUE TITLE
Support for globally renaming fields

### ISSUE THREAD

**Issue by fkrauthan** [SMILEY4/schema-kenerator#18]
I have a use-case where all my field names should be snake case. KotlinX Serialization has a feature where you can specify the json naming strategy like this:

```
val jsonFormat = Json {
    namingStrategy = JsonNamingStrategy.SnakeCase
}
```

Is there any way to adjust the naming globally for the schema generation (I am actually using the ktor swagger library primarily)?

**Comment by SMILEY4** [comment]
Thank you for the suggestion. 
There is currently no "official" way, though you could write your own custom step.
An additional step for renaming properties will be included in the next version though.
