### ISSUE TITLE
schema-kenerator-swagger - @Required annotation doesn't work if all properties are nullable and/or optional

### ISSUE THREAD

**Issue by Skater901** [SMILEY4/schema-kenerator#19]
I'm not certain if this is intentional or not, but when documenting a class where all properties are nullable and/or optional, using the `@Required` annotation doesn't do anything.

When the Swagger `Schema` object is created, and `setRequired` is called, if the list provided to `setRequired` is empty, the private field `required` will be set to null. If all fields of an object are nullable or optional, the list of required fields provided to the `Schema` object [will be empty](https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-swagger/src/main/kotlin/io/github/smiley4/schemakenerator/swagger/steps/SwaggerSchemaGenerationStep.kt#L153-L154).

Then, when the `@Required` annotations are processed, if the `Schema` object has no List for the `required` property, a [new list is created](https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-swagger/src/main/kotlin/io/github/smiley4/schemakenerator/swagger/steps/SwaggerSchemaCoreAnnotationOptionalAndRequiredStep.kt#L45). But because this List is never assigned to the `Schema` object, the results of the annotation processing are lost.

I'm not sure if this is intentional, but if it is, it would be good to document the behaviour somewhere. (It might already be documented and I missed it.) However, it seems strange that the annotations would still be processed, but the results ignored. Especially since I could fix this behaviour simply by making 1 property not nullable or optional.

**Comment by SMILEY4** [comment]
this is not intentional and the bug will be fixed in the next version. Thanks!
