### ISSUE TITLE
ClassWithLocalDateTime was excluded from the KotlinxSerializationParser_SwaggerGenerator_Tests.!!!

### ISSUE THREAD

**Issue by kchinburarat** [SMILEY4/schema-kenerator#25]
I noticed that @SMILEY4 excluded this from the unit test:
https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-test/src/test/kotlin/io/github/smiley4/schemakenerator/test/KotlinxSerializationParser_SwaggerGenerator_Tests.kt#L1014

What are the current known issues preventing us from testing it?
```
@Serializable
class ClassWithLocalDateTime(
    @Serializable(with = LocalDateTimeSerializer::class)
    val dateTime: LocalDateTime
)
```

**Comment by SMILEY4** [comment]
Hi, I *think* this was a leftover from a refactoring and can be removed. The same functionality should be covered here: https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-test/src/test/kotlin/io/github/smiley4/schemakenerator/test/CustomLocalDateTimeTypeProcessorTest.kt
