### ISSUE TITLE
Swagger inline nullable schemas types are resolved to `any` instead of `(T | null)`

### ISSUE THREAD

**Issue by rmcmk** [SMILEY4/schema-kenerator#28]
```kt

@Serializable
data class Sample(
    val string: String,
    val string2: String,
    val string3: String,
    val string4: String?
)

@Serializable
data class Sample2(
    val string: String? = null
)

@Serializable
data class Sample3(
    val string: String?
)

@Serializable
data class Sample4(
    val string: String?,
    val string2: String,
    val string3: String? = null,
    val string4: String
)
```

![image](https://github.com/user-attachments/assets/c408c883-92c8-40fd-953d-3d7ed2498762)

As per the [Swagger docs](https://swagger.io/docs/specification/v3_0/data-models/data-types/#mixed-types) the resolution step in [SwaggerSchemaCompileInlineStep](https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-swagger/src/main/kotlin/io/github/smiley4/schemakenerator/swagger/steps/SwaggerSchemaCompileInlineStep.kt#L25-L34) and [SwaggerSchemaCompileReferenceStep](https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-swagger/src/main/kotlin/io/github/smiley4/schemakenerator/swagger/steps/SwaggerSchemaCompileReferenceStep.kt#L63-L72) is incorrect.

Locally, I've applied a fix to both resolution steps:

```kt
  merge(refObj, referencedSchema.swagger).also {
      if (it.nullable == true) {
          it.oneOf = listOf(referencedSchema.swagger, schemaUtils.nullSchema())
          it.type = null
      }
      it.nullable = null
  }
```

which results in:

![image](https://github.com/user-attachments/assets/20101c9c-6cb2-46d6-9119-bdc0b91a8cc7)

However, I'm not 100% familiar with the openapi spec, this may not be correct, either.

**Comment by NecroKote** [comment]
Hey @rmcmk, thanks for your report!

I'm assuming you are using [ktor-swagger-ui](https://github.com/SMILEY4/ktor-swagger-ui) to render the schema?
If so, I've opened the issue in that repo that should fix this behaviour. 

In short, kenerator correctly generates the schema (v 3.1), it's the rendering of it that causes the observed behaviour (rendered as v3.0).

You can read more about it in this SO [answer](https://stackoverflow.com/a/48114322)

**Comment by rmcmk** [comment]
Yes, that's correct. Thanks!

**Comment by SMILEY4** [comment]
Hi, thanks you.
@NecroKote PR together with a [fix](https://github.com/SMILEY4/schema-kenerator/compare/fix-types-openapi31?expand=1) (should have changed some "type" to "types") should resolve this issue.
