### ISSUE TITLE
Include discriminator field for sealed classes

### ISSUE THREAD

**Issue by rChaoz** [SMILEY4/schema-kenerator#3]
**Note:** This issue is about the `kotlinx.serialization` generator.

## Description

Given the code:

```kotlin
@Serializable
sealed class Parent

@Serializable
data class ChildOne(val text: String)

@Serializable
data class ChildTwo(val number: Int)

val one = ChildOne("some_text")
val two = ChildTwo(123)
```

There is a difference between serializing `one` as `Parent` or as `ChildOne`:

- `Json.encodeToString(one)` &rarr; `{ "text": "some_text" }`
- `Json.encodeToString<Parent>(one)` &rarr; `{ "type": "package.name.ChildOne", "text": "some_text" }`

The field name (here the default - `type`) can be changed by annotating the parent class with `@JsonClassDiscriminator`, and the values by annotating the child classes with `@SerialName`:

```kotlin

@Serializable
@JsonClassDiscriminator("the_type")
sealed class Parent

@Serializable
@SerialName("child_one")
data class ChildOne(val text: String)

@Serializable
@SerialName("child_two")
data class ChildTwo(val number: Int)
```

Then:

- `Json.encodeToString<Parent>(one)` &rarr; `{ "the_type": "child_one", "text": "some_text" }`

## Issue

The generated schemas do not currently contain the type discriminator field.

## Example

Given the data types:

```kotlin
@Serializable
sealed class Response

@Serializable
@SerialName("auth_failed")
data class AuthFailedResponse(
    val reason: String,
    val description: String,
    val scopes: String? = null
) : Response()

@Serializable
@SerialName("success")
data class SuccessfulResponse(val data: Data) : Response()
```

And the following config (schemas displayed using swagger-ui):

```kotlin
schemas {
    generator = { type ->
        type
            .processKotlinxSerialization()
            .connectSubTypes()
            .generateSwaggerSchema()
            .withAutoTitle(TitleType.SIMPLE)
            .compileReferencingRoot()
    }
}
```

Result:

<img width="364" alt="image" src="https://github.com/SMILEY4/schema-kenerator/assets/8215371/9d55ac99-627e-4499-af4f-8b27baa4eea4">

## Note

There doesn't seem to be any literal values support, so this would be tricky to fix.

**Comment by rmcmk** [comment]
> Note: This issue is about the kotlinx.serialization generator.

Am able to reproduce with my own test case, occurs with both kotlinx and reflection generators.

**Comment by SMILEY4** [comment]
sorry this took so long, but support for discriminators (i.e. additional step) will finally be included in the next version.
