### ISSUE TITLE
The `default` property of core annotation `@Default` gets stripped when stubbed with kapt

### ISSUE THREAD

**Issue by rmcmk** [SMILEY4/schema-kenerator#34]
This one is weird. The only annotation affected is `@Default` (all other core annotations appear fine) This could be a bug with [schema-kenerator](https://github.com/SMILEY4/schema-kenerator), [kapt](https://kotlinlang.org/docs/kapt.html) or [avaje-inject](https://github.com/avaje/avaje-inject)

Placing `@Default("xyz")` on any type or property produces the stub (generated by kapt):

```kt
@Default("asc")
enum class OrderBy {
    ASC,
    DESC,
}
```

```java
@kotlinx.serialization.Serializable()
@io.github.smiley4.schemakenerator.core.annotations.Default()
public enum OrderBy {
    // ... remainder omitted for brevity 
```

As you can see, the parameter gets stripped, resulting in:

```
/home/rmcmk/project/build/tmp/kapt3/stubs/main/very/cool/package/names/OrderBy.java:9: error: annotation @Default is missing a default value for the element 'default'
@io.github.smiley4.schemakenerator.core.annotations.Default()
^
```

The only difference I physically see from the other annotations is that `val default: String` is not documented with KDoc, which really shouldn't matter?

[Default.kt](https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-core/src/main/kotlin/io/github/smiley4/schemakenerator/core/annotations/Default.kt#L7)
[Description.kt](https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-core/src/main/kotlin/io/github/smiley4/schemakenerator/core/annotations/Description.kt#L8)

Wondering if anyone else is using kapt (perhaps from another library than avaje-inject?) having a similar issue?

Edit: It's the name of the parameter... `default` is a restricted java keyword.. duh. Been awhile...

**Comment by SMILEY4** [comment]
ah,  mmh, the java keyword ...    thanks for the fix :sweat_smile:  :+1:
