### ISSUE TITLE
Using Non-nullable and nullable type in the same class appends random numbers to the second type.

### ISSUE THREAD

**Issue by K1rakishou** [SMILEY4/schema-kenerator#37]
Hi. After trying to update to the latest version, I have noticed this behavior.

![Screenshot 2567-10-16 at 11 52 58](https://github.com/user-attachments/assets/b221e74c-c752-48fc-a2c5-d17c902182f0)

![Screenshot 2567-10-16 at 11 53 12](https://github.com/user-attachments/assets/e89f4518-6125-497f-a98e-62365d17ec73)

They are both the same type, but one is nullable, the other one is non-nullable. 

The problem seems to be in KotlinxSerializationTypeProcessingStep.kt

```
private fun getUniqueId(descriptor: SerialDescriptor, typeParameters: List<TypeId>, typeData: MutableList<BaseTypeData>): TypeId {
    if (knownNotParameterized.contains(descriptor.cleanSerialName())) {
        return TypeId.build(descriptor.cleanSerialName(), typeParameters)
    }
    if (typeData.find(descriptor, typeParameters) != null) {
        return TypeId.build(descriptor.cleanSerialName(), typeParameters, true)
    }
    return TypeId.build(descriptor.cleanSerialName(), typeParameters)
}

private fun Collection<BaseTypeData>.find(descriptor: SerialDescriptor, typeParameters: List<TypeId>): BaseTypeData? {
    val typeId = TypeId.build(descriptor.cleanSerialName(), typeParameters)
    return this.find { it.id.full() == typeId.full() }
}
```

When checking if the type is already defined
```
if (typeData.find(descriptor, typeParameters) != null) {
```
the nullability information is removed from full type name. Here we can see that the type is nullable:
![Screenshot 2567-10-16 at 13 17 54](https://github.com/user-attachments/assets/9396294a-1fd9-49f6-80af-2026c707e944)

But then when creating a type for searching `descriptor.cleanSerialName()` is used:
```
val typeId = TypeId.build(descriptor.cleanSerialName(), typeParameters)
```
where `cleanSerialName()` is removing the `?`:
```
private fun SerialDescriptor.cleanSerialName() = this.serialName.replace("?", "")
```
Because of that `typeData.find(descriptor, typeParameters) != null` returns non-null value and `getUniqueId` returns TypeId with random value added to it (`withAdditionalId` is true).

If I remove nullability from `second` parameter then everything works as expected. Also if I reorder `first` and `second` fields in `TestType` then `first` field will have random numbers added to it instead of `second` which is nullable. So the problem is not in using nullability but in checking if a type was already defined to deduplicate them.

I have tried to use a `typeRedirect` from `Something?` -> `Something` but unfortunately it didn't help.

**Comment by SMILEY4** [comment]
Hi,
this comes from the limitation from kotlinx-serialization where it drops information about generic types, e.g.:
```kotlin
class TestType(
    val first: SomeType<String>,
    val second: SomeType<Int>,
)
```
I need to handle `SomeType<String>` and `SomeType<Int>` as two different types that generate different schemas, but kotlinx "only" keeps the information that it is `SomeType`.
The workaround I decided on was to duplicate types that were already encountered, resulting in `SomeType` and `SomeType#12345`. Without that, information about the generic type could be mixed up and e.g. both `SomeType`s would be incorrectly treated as `SomeType<String>` or `SomeType<Int>`.
Unfortunatly, this behavior can also affect types/setups, where this would not be needed (like in your case).

I'm not sure if there is another reliable solution, approach or way to detect that two types have different/same/no type parameters :thinking: 

A workaround to manually fix your problem would be to tell the processing step that the type does not have generic type parameters and that this behavior is not neccesary.
```kotlin
//...
.processKotlinxSerialization {
    markNotParameterized<Something>()
}
//...
```

**Comment by K1rakishou** [comment]
I see. Indeed, using `markNotParameterized<Something>()` solves the issue. Thank you!

**Comment by anderssonw** [comment]
@SMILEY4 

Is there any recommended workaround for the class that is being numbered like Something#12345, when the class actually has a generic parameter?

I would not like to mark every single possible type parameter I can think of for the class 😭
