### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Him188** [SMILEY4/schema-kenerator#40]
![image](https://github.com/user-attachments/assets/9f63ba63-66aa-42ae-b86d-f1050d641524)

My build scripts:
```kotlin
    implementation("io.github.smiley4:schema-kenerator-core:1.5.0")
    implementation("io.github.smiley4:schema-kenerator-serialization:1.5.0")
    implementation("io.github.smiley4:schema-kenerator-swagger:1.5.0")
```

I guess it's because schema-kenerator added a `implementation` dependency on swagger Schema instead of `api()`. We probably should use `api`.

**Comment by SMILEY4** [comment]
Hi, thanks for the suggestion. Changed to api with the next version
