### ISSUE TITLE
Unable to Create Schemas with Generic Objects with Kotlinx Serialization

### ISSUE THREAD

**Issue by ragboyjr** [SMILEY4/schema-kenerator#41]
Hi! Thank you so much for maintaining this package, it's been really great.

I just recently came across an issue (tested on 1.6.0) when using the `schema-kenerator-serialization` package where it wouldn't serialize generic classes as I expected. It looks like the `schema-kenerator-reflection` works as one would expect.

Here's an example test case highlighting the differences:

```kotlin
    @Serializable
    data class Generic<T>(
        val item: T,
    )

    fun Bundle<BaseTypeData>.toJson() = generateJsonSchema()
        .withTitle(TitleType.SIMPLE)
        .compileInlining()
        .json
        .prettyPrint()

    @Test
    fun `can generate schema on generic classes`() {
        assertEquals(
            """
            {
               "type": "object",
               "required": [
                  "item"
               ],
               "properties": {
                  "item": {
                     "type": "integer",
                     "minimum": -2147483648,
                     "maximum": 2147483647,
                     "title": "Int"
                  }
               },
               "title": "Generic<Int>"
            }
            """.trimIndent(),
            typeOf<Generic<Int>>().processReflection().toJson(),
        )
        
        // Issue is here: I expected this to match the same reflection based processing, but instead got just an object
        assertEquals(
            """
            {
               "type": "object",
               "title": "*"
            }
            """.trimIndent(),
            typeOf<Generic<Int>>().processKotlinxSerialization().toJson(),
        )
    }
```

Is this expected behavior? I read some other comments that kotlinx serialization doesn't provide a ton of info for generic types, so not sure if this is just a known limitation of the kotlinx serialization module.

**Comment by ragboyjr** [comment]
Lol, never mind, i didn't see this: https://github.com/SMILEY4/schema-kenerator/blob/develop/schema-kenerator-test/src/test/kotlin/io/github/smiley4/schemakenerator/test/KotlinxSerializationParser_JsonGenerator_Tests.kt#L459

**Comment by SMILEY4** [comment]
Hi,
i looked at this "issue" again and actual found a solution/fix for it - so this should now be properly working in 1.6.2

**Comment by ragboyjr** [comment]
Wow! amazing! will check this out, thank you so much!
