### ISSUE TITLE
processKotlinxSerialization is not generating swagger schema properly for Lists<CustomObject> and Individual CustomObject present in same class

### ISSUE THREAD

**Issue by m-umar-bilal** [SMILEY4/schema-kenerator#5]
Hi,
I found a bug in schema-kenerator version 1.0.1(using with ktor-swagger-ui version 3.2.0) related to OpenAPI and schema generation using Kotlin serialization. The issue occurs when you have both a list of custom objects and individual custom objects as fields in the same data class.

**Example Setup**
Ktor Swagger UI Configuration

```kotlin
install(SwaggerUI) {
    schemas {
        // Customized schema generation pipeline
        generator = { type ->
            type
                .processKotlinxSerialization()
                .generateSwaggerSchema()
                .withAutoTitle(TitleType.SIMPLE) // Use the simple class names for titles.
                .compileReferencing(RefType.SIMPLE) // Use the simple class names for references.
        }
    }
}
```
Data Model

```kotlin
package com.example
import kotlinx.serialization.Serializable

@Serializable
data class TestRequest(
    val items: List<Item>? = null,
    val selectedItem: Item? = null,
) {
    @Serializable
    data class Item(
        val id: Int? = null,
        val name: String? = null
    )
}
```
**Issue**

The generated schema is incorrect when you have a List<CustomObject> as one of the fields and also CustomObject without a list as one of the fields. For example, the generated schema for the above example would be:

```json
"TestRequest": {
                "title": "TestRequest",
                "type": "object",
                "properties": {
                    "items": {
                        "title": "ArrayList<Item>",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Item"
                        }
                    },
                    "selectedItem": {
                        "$ref": "#/components/schemas/Item#8127298379063018757"
                    }
                }
            }
```

Notice the random suffix #8127298379063018757.

If the order of the` List<Item>` is changed, for example:

```kotlin
package com.example
import kotlinx.serialization.Serializable

@Serializable
data class TestRequest(
    val selectedItem: Item? = null,
    val items: List<Item>? = null,
) {
    @Serializable
    data class Item(
        val id: Int? = null,
        val name: String? = null
    )
}

```
The generated schema becomes:

```json
"TestRequest": {
                "title": "TestRequest",
                "type": "object",
                "properties": {
                    "selectedItem": {
                        "$ref": "#/components/schemas/Item"
                    },
                    "items": {
                        "$ref": "kotlin.collections.ArrayList<com.example.TestRequest.Item#6357439241701235850>"
                    }
                }
            }
```
In this case, the reference `kotlin.collections.ArrayList<com.example.TestRequest.Item#6357439241701235850>` doesn't exist at all.

**Summary**
The issue seems to be related to the order of fields in the data class when generating the schema. The schema generation process should handle lists and individual custom objects consistently, regardless of their order in the data class.

Thanks so much.

**Comment by SMILEY4** [comment]
Hi,

the underlying issue is that i (as far as i know) kotlinx does not keep/provide information about generic type parameters.

For example:
```kotlin
@Serializable
class Item<T>(val value: T)

class Request(
   val a: Item<String>,
   val b: Item<Int>
)
```
Here i would need to generate different schemas (and ids) for the type Item<String> and one for Item<Int>, but since (afaik) cannot know if it even has a generic type parameter (i "only" have the name of the type), i assign a unique id to classes when i encounter them multiple times.

Maybe one solution would be to have a flag to tell the generator that no generic types are involved and it can safely assign the same ids / create the same schemas for types with the same name.

**Comment by SMILEY4** [comment]
i`ll close this issue. Unfortunately, as far is i know, there is not much i can do in terms of automatically handling these scenarios in a reliable way.

I did add a change in 1.1.0

> added config option `knownNotParameterized` for type processing with kotlinx-serialization to manually prevent single type appearing multiple times in some setups

that allows marking classes as "definitely not having any generic types" which then allows the generator to handle these a bit differently.
