### ISSUE TITLE
NPE in ReflectionTypeProcessingStep.kt

### ISSUE THREAD

**Issue by vincentburesi-es** [SMILEY4/schema-kenerator#6]
As stated in documentation of KClass.qualifiedName is nullable in certain circumstances.

> The fully qualified dot-separated name of the class, or null if the class is local or a class of an anonymous object.

The function io.github.smiley4.schemakenerator.reflection.steps.ReflectionTypeProcessingStep#parseClass asserts that qualifiedName is non-null at line 227 which causes a NullPointerException whenever the class sent is a local or anonymous object class. Same issue might happen also on TypeCategory ENUM, COLLECTION and MAP

```kotlin
TypeCategory.OBJECT -> ObjectTypeData(
    id = id,
    simpleName = clazz.simpleName!!,
    qualifiedName = clazz.qualifiedName!!, // <-- qualifiedName might be null here
    typeParameters = resolvedTypeParameters.toMutableMap(),
    subtypes = subtypes.toMutableList(),
    supertypes = supertypes.toMutableList(),
    members = members.toMutableList(),
    annotations = annotations.toMutableList()
)
```

I had the issue while trying to test the ktor-swagger-ui library while defining the class near the route I was testing. I am unsure of the implications or rationality of supporting local/anonymous classes, but if unsupported it would be great to have an explicit error explaining it.

**Comment by SMILEY4** [comment]
Hi,  thanks for the report,

for local classes / when the qualified name is missing, i think i can simply use `MyClass::class.java.name` instead of `MyClass::class.qualifiedName`.
This should fix this issue and will be included in the next version.
